# Generated by Django 4.0.1 on 2022-02-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Search_Item', models.CharField(help_text='Enter your Required News', max_length=100)),
            ],
        ),
    ]
