# Generated by Django 4.0.1 on 2022-02-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewsUpdates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBackDetailsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Person_Name', models.CharField(help_text='Enter person Name', max_length=100)),
                ('Suggested_Name', models.CharField(help_text='Enter your Suggested news', max_length=100)),
                ('Feedback_Text', models.TextField(help_text='please give your suggestions to improve', max_length=900)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
